== global.el

=== Purpose

* Provide a (unit-) testeable Emacs Lisp API that wraps `global` binary calls (exposed to developer).
* Optional integration to Emacs using aformentioned API with `project.el` and `xref.el` (exposed to final user).

=== Secondary purposes

* Integrate to main Emacs branch
* Do *not* expose `global` to the final user with commands: user should use `project.el` and `xref.el` functions
* Improve response times of queries in remote or big codebase by pre-fetching results in the background.

=== Usage

You can setup using GNU global as backend with any of the following two lines:

[source,elisp]
----
;; to use GNU Global automagically, regardless of Emacs default configuration
(add-hook 'ruby-mode-hook #'global-tags-exclusive-backend-mode)
;; to use GNU Global automagically, respecting other backends
(add-hook 'ruby-mode-hook #'global-tags-shared-backend-mode)
----

Alternatively, you can manually configure project.el and xref.el, add their
"recognize this global handled project" to the proper places like so:

[source,elisp]
----
;; xref (finding definitions, references)
(add-to-list 'xref-backend-functions 'global-tags-xref-backend)
;; project.el (finding files)
(add-to-list 'project-find-functions 'global-tags-try-project-root)
;; to update database after save
(add-hook 'c++-mode-hook (lambda ()
                           (add-hook 'after-save-hook
                                     #'global-tags-update-database-with-buffer
                                     nil
                                     t)))
----

=== Reporting bugs

https://bugs.launchpad.net/global-tags.el

=== Submiting patches / pull requests

See https://help.launchpad.net/Code/Review/#Proposing_a_merge and https://answers.launchpad.net/launchpad/+question/267929 as stated https://bugs.launchpad.net/global-tags.el/+bug/1844961[here]

=== Code of Conduct

Please note that this project is released with a Contributor Code of Conduct. By participating in this project you agree to abide by its terms.

=== Related projects

* https://www.gnu.org/s/global/[GNU global]: source code tag system
* https://github.com/syohex/emacs-counsel-gtags[counsel-gtags]: unmaintained and non-re-usable https://github.com/abo-abo/swiper[counsel] interface. (my maintained fork https://github.com/FelipeLema/emacs-counsel-gtags/[here])
* https://github.com/leoliu/ggtags[ggtags]: interface using `compilation-mode`. Not a re-usable library (see https://github.com/leoliu/ggtags/issues/175#issuecomment-428986369[here])
* https://github.com/dedi/gxref/[gxref]: unmaintained
* https://github.com/alexmurray/ivy-xref: Use Ivy for xref commands.
* https://github.com/syohex/emacs-helm-gtags[helm-gtags]: unmaintained
* https://github.com/vietor/agtags[agtags]: no testscript up to date, provides custom interface to final user (adds shortcuts to new commands)
